from autos import Coche

lista = [
    Coche("Ford", "Mustang", 2020, "Azul"),
    Coche("Chevrolet", "Camaro", 2019, "Rojo"),
    Coche("BMW", "X5", 2022, "Negro"),
    Coche("Audi", "A4", 2021, "Blanco"),
    Coche("Tesla", "Model 3", 2023, "Gris"),
    Coche("Toyota", "Corolla", 2020, "Plateado"),
    Coche("Honda", "Civic", 2022, "Azul"),
    Coche("Mercedes-Benz", "Clase C", 2021, "Negro"),
    Coche("Porsche", "911", 2023, "Amarillo"),
    Coche("Volkswagen", "Golf", 2018, "Blanco"),
    Coche("Nissan", "GT-R", 2021, "Naranja"),
    Coche("Hyundai", "Tucson", 2022, "Verde"),
    Coche("Kia", "Sportage", 2021, "Rojo"),
    Coche("Mazda", "MX-5", 2020, "Gris"),
    Coche("Subaru", "WRX", 2022, "Azul"),
    Coche("Jeep", "Wrangler", 2023, "Verde Militar"),
    Coche("Dodge", "Challenger", 2021, "Morado"),
    Coche("Lexus", "RX", 2022, "Blanco"),
    Coche("Volvo", "XC90", 2021, "Azul Oscuro"),
    Coche("Land Rover", "Defender", 2022, "Arena"),
    Coche("Ferrari", "488", 2020, "Rojo"),
    Coche("Lamborghini", "Huracan", 2022, "Verde"),
    Coche("McLaren", "720S", 2021, "Naranja"),
    Coche("Aston Martin", "DB11", 2020, "Plateado"),
    Coche("Bentley", "Continental", 2022, "Azul"),
    Coche("Rolls-Royce", "Ghost", 2023, "Negro"),
    Coche("Maserati", "Ghibli", 2021, "Blanco"),
    Coche("Jaguar", "F-Type", 2022, "Verde Británico"),
    Coche("Mini", "Cooper", 2021, "Rojo con Blanco"),
    Coche("Fiat", "500", 2020, "Cian"),
    Coche("Alfa Romeo", "Giulia", 2022, "Rojo"),
    Coche("Peugeot", "3008", 2021, "Gris"),
    Coche("Renault", "Megane", 2020, "Azul"),
    Coche("Citroën", "C5 Aircross", 2022, "Blanco"),
    Coche("Seat", "Leon", 2021, "Rojo"),
    Coche("Cupra", "Formentor", 2023, "Gris Mate"),
    Coche("Skoda", "Octavia", 2022, "Azul"),
    Coche("Mitsubishi", "Lancer", 2017, "Blanco"),
    Coche("Suzuki", "Swift", 2021, "Amarillo"),
    Coche("Cadillac", "Escalade", 2023, "Negro"),
    Coche("Lincoln", "Navigator", 2022, "Azul"),
    Coche("Buick", "Enclave", 2021, "Champán"),
    Coche("GMC", "Sierra", 2022, "Rojo"),
    Coche("Ram", "1500", 2023, "Gris"),
    Coche("Chrysler", "300", 2020, "Negro"),
    Coche("Genesis", "G80", 2022, "Plateado"),
    Coche("Infiniti", "Q50", 2021, "Blanco"),
    Coche("Acura", "NSX", 2022, "Rojo"),
    Coche("Lotus", "Emira", 2023, "Azul"),
    Coche("Bugatti", "Chiron", 2021, "Azul Carbono")
]

# Ejecución del método
for s in lista:
    s.descripcion()